version: '3'
services:
  podcast-sponsor-block:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: podcast-sponsor-block
    hostname: podcast-sponsor-block
    volumes:
      - "/mnt/data/media/podcast-sponsor-block:/app/data"
    ports:
      - "7637:7637"